type: l2leaf
l2leaf:
  nodes:
    - name: platform_settings

platform_settings:
  - platforms: [ default ]
    # Test for security_entropy_sources
    security_entropy_sources:
      hardware: true
      haveged: true
      cpu_jitter: true
      hardware_exclusive: true
    # Test for structured_config
    structured_config:
      ethernet_interfaces:
        - name: Ethernet12
          switchport:
            enabled: true
          description: Interface Created from platform_settings.structured_config
