# Project information
site_name: Arista AVD
site_author: Arista Ansible Team
site_description: Arista Validated Designs documentation
copyright: Copyright &copy; 2019 - 2025 Arista Networks
strict: true
exclude_docs: |
  /README.md

# Repository information
repo_name: AVD on Github
repo_url: https://github.com/aristanetworks/avd

# Configuration
use_directory_urls: false
edit_uri: edit/devel/
theme:
  name: material
  features:
    - content.code.annotate
    - content.code.copy
    - content.tabs.link
    - header.autohide
    - navigation.instant
    - navigation.prune
    - navigation.top
    - search.highlight
    # - toc.integrate
    - toc.follow
  highlightjs: true
  icon:
    repo: fontawesome/brands/github
    logo: fontawesome/solid/book
    edit: fontawesome/solid/file-pen
  favicon: docs/_media/favicon.ico
  font:
    code: Fira Mono
  language: en
  include_search_page: false
  search_index_only: true
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/weather-night
        name: Switch to light mode

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/aristanetworks/avd
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/AristaNetworks
    - icon: fontawesome/solid/globe
      link: https://www.arista.com
  version:
    provider: mike
    default: stable

extra_css:
  - docs/stylesheets/extra.material.css

extra_javascript:
  - https://unpkg.com/tablesort@5.3.0/dist/tablesort.min.js
  - docs/stylesheets/tables.js

plugins:
  - exclude:
      glob:
        - README.md
        - contributing.md
        - ansible_collections/arista/avd/bindep.txt
        - ansible_collections/arista/avd/CHANGELOG.rst
        - ansible_collections/arista/avd/CNAME
        - ansible_collections/arista/avd/collections.yml
        - ansible_collections/arista/avd/galaxy.yml
        - ansible_collections/arista/avd/LICENSE
        - ansible_collections/arista/avd/pylintrc
        - ansible_collections/arista/avd/pytest.ini
        - ansible_collections/arista/avd/README.md
        - ansible_collections/arista/avd/requirements-dev.txt
        - ansible_collections/arista/avd/requirements.txt
        - ansible_collections/arista/avd/meta/*
        - ansible_collections/arista/avd/playbooks/*
        - ansible_collections/arista/avd/plugins/*
        - ansible_collections/arista/avd/changelogs/*
        - ansible_collections/arista/avd/molecule/*
        - ansible_collections/arista/avd/tests/*
        - ansible_collections/arista/avd/plugins/README.md
        - docs/release-notes/1.0.x.md
        - docs/release-notes/1.1.x.md
        - docs/release-notes/2.x.x.md
        - docs/release-notes/3.x.x.md
        - docs/release-notes/4.x.x.md
        - docs/porting-guides/4.x.x.md
        - ansible_collections/arista/avd/roles/*/docs/tables/*
        - development/*
        - galaxy-importer/*
        - python-avd/*
      regex:
        # Exclude examples common md snippets
        - 'ansible_collections\/arista\/avd\/examples\/common/.*'
        # Exclude all examples but single-dc-l3ls which is referenced in getting getting-started
        - 'ansible_collections\/arista\/avd\/examples\/((?!single-dc-l3ls).*)\/documentation\/.*'
        # Exclude all single-dc-l3ls files not referenced in getting getting-started
        - 'ansible_collections\/arista\/avd\/examples\/single-dc-l3ls\/documentation\/fabric\/((?!FABRIC-documentation.md).*)'
        - 'ansible_collections\/arista\/avd\/examples\/single-dc-l3ls\/documentation\/devices\/((?!dc1-leaf1a.md).*)'
        - '.*.py$'
        - '.*.pyc$'
        - '.*.j2$'
  - include_dir_to_nav
  - git-revision-date-localized:
      type: date
  - search:
      lang: en
  - mkdocstrings:
      handlers:
        python:
          paths:
            - python-avd
  - same-dir

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - mdx_truly_sane_lists
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols:
      fractions: false
  - pymdownx.snippets:
      base_path:
        - './'
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - smarty
  - tables
  - toc:
      separator: "-"
      permalink: true

# TOC
docs_dir: .
nav:
  - Home: index.md
  - Getting Started:
      - Introduction to Ansible and AVD: docs/getting-started/intro-to-ansible-and-avd.md
      - AVD and Ansible Automation Platform: docs/getting-started/avd-aap.md
  - Examples:
      - Single DC L3LS: ansible_collections/arista/avd/examples/single-dc-l3ls/README.md
      - Dual DC L3LS: ansible_collections/arista/avd/examples/dual-dc-l3ls/README.md
      - L2LS Fabric: ansible_collections/arista/avd/examples/l2ls-fabric/README.md
      - Campus Fabric: ansible_collections/arista/avd/examples/campus-fabric/README.md
      - ISIS-LDP IPVPN: ansible_collections/arista/avd/examples/isis-ldp-ipvpn/README.md
      - CV Pathfinder: ansible_collections/arista/avd/examples/cv-pathfinder/README.md
  - Installation:
      - Collection Installation: docs/installation/collection-installation.md
  - Ansible Collection Roles:
      - eos_designs:
          - Overview: ansible_collections/arista/avd/roles/eos_designs/README.md
          - Role Configuration: ansible_collections/arista/avd/roles/eos_designs/docs/role-configuration.md
          - Input Variables: ansible_collections/arista/avd/roles/eos_designs/docs/input-variables.md
          - How-To Guides:
              - Configuring PTP: ansible_collections/arista/avd/roles/eos_designs/docs/how-to/ptp.md
              - Configuring WAN: ansible_collections/arista/avd/roles/eos_designs/docs/how-to/wan.md
              - Custom descriptions and names: ansible_collections/arista/avd/roles/eos_designs/docs/how-to/custom-descriptions-names.md
              - Custom Structured Configuration: ansible_collections/arista/avd/roles/eos_designs/docs/how-to/custom-structured-configuration.md
              - Custom Templates: ansible_collections/arista/avd/roles/eos_designs/docs/how-to/custom-templates.md
              - Generate CloudVision Tags Preview: ansible_collections/arista/avd/roles/eos_designs/docs/how-to/cloudvision-tags-preview.md
      - eos_cli_config_gen:
          - Overview: ansible_collections/arista/avd/roles/eos_cli_config_gen/README.md
          - Role Configuration: ansible_collections/arista/avd/roles/eos_cli_config_gen/docs/role-configuration.md
          - Input Variables: ansible_collections/arista/avd/roles/eos_cli_config_gen/docs/input-variables.md
          - How-To Guides:
              - Custom Templates: ansible_collections/arista/avd/roles/eos_cli_config_gen/docs/how-to/custom-templates.md
      - cvp_configlet_upload: ansible_collections/arista/avd/roles/cvp_configlet_upload/README.md
      - eos_config_deploy_cvp:
          - Overview: ansible_collections/arista/avd/roles/eos_config_deploy_cvp/README.md
          - Integrating AVD with CVaaS: ansible_collections/arista/avd/roles/eos_config_deploy_cvp/docs/avd-to-cvaas.md
      - eos_config_deploy_eapi: ansible_collections/arista/avd/roles/eos_config_deploy_eapi/README.md
      - eos_validate_state: ansible_collections/arista/avd/roles/eos_validate_state/README.md
      - eos_snapshot: ansible_collections/arista/avd/roles/eos_snapshot/README.md
      - dhcp_provisioner: ansible_collections/arista/avd/roles/dhcp_provisioner/README.md
      - build_output_folders: ansible_collections/arista/avd/roles/build_output_folders/README.md
      - cv_deploy: ansible_collections/arista/avd/roles/cv_deploy/README.md
  - Ansible Collection Plugins: docs/plugins/
  - Contributing to AVD:
      - Overview: docs/contribution/overview.md
      - Development Tooling: docs/contribution/development-tooling.md
      - Code Style: docs/contribution/style-guide.md
      - Validation of Input Variables: docs/contribution/input-variable-validation.md
      - EOS Designs internal notes: docs/contribution/eos_designs_internal_notes.md
      - Authoring eos_cli_config_gen Role Guide: docs/contribution/authoring_eos_cli_config_gen.md
  - Release Notes: docs/release-notes/5.x.x.md
  - Porting Guide: docs/porting-guides/5.x.x.md
  - PyAVD: docs/pyavd/pyavd.md
  - Versioning: docs/versioning/semantic-versioning.md
  - AVD Dev Containers:
      - Overview: docs/containers/overview.md
