---
## AAA Accounting
aaa_accounting:
  exec:
    console:
      type: start-stop
      group: TACACS
      logging: true
    default:
      type: start-stop
      group: TACACS
      logging: true
  system:
    default:
      type: start-stop
      group: TACACS
  dot1x:
    default:
      type: start-stop
      group: RADIUS
  commands:
    console:
      - commands: all
        type: start-stop
        group: TACACS
        logging: true
      - commands: 0
        type: start-stop
        logging: true
      - commands: 1
        type: start-stop
        logging: false
        group: TACACS1
      # As type is none hence logging will not render in config as per actual EOS
      - commands: 2
        type: none
        logging: true
      # If type is start-stop or stop-only then logging should be true or group should be defined to render the config
      - commands: 3
        type: start-stop
        logging: false
    default:
      - commands: all
        type: start-stop
        group: TACACS
        logging: true
      - commands: 0
        type: start-stop
        logging: true
        # To handle the missing case
      - commands: 1
        type: start-stop
        logging: false
        group: TACACS
      # As type is none hence logging will not render in config as per actual EOS
      - commands: 2
        type: none
        logging: true
      # If type is start-stop or stop-only then logging should be true or group should be defined to render the config
      - commands: 3
        type: start-stop
        logging: false
