---
### IPv6 ACLs ###
ipv6_access_lists:
  - name: acl_qos_tc0_v6
    sequence_numbers:
      - sequence: 10
        action: "permit ipv6 any any dscp cs1"
  - name: acl_qos_tc5_v6
    sequence_numbers:
      - sequence: 10
        action: "permit ipv6 any 2001:db8::/48"
  - name: TEST1
    sequence_numbers:
      - sequence: 10
        action: "permit ipv6 fe90::/64 any"
      - sequence: 5
        action: "deny ipv6 fe80::/64 any"
  - name: TEST2
    counters_per_entry: true
    sequence_numbers:
      - sequence: 5
        action: "permit ipv6 2001:db8::/64 any"
      - sequence: 10
        action: "deny ipv6 2001:db8::/32 any"
  - name: TEST3
    counters_per_entry: false
    sequence_numbers:
      - sequence: 5
        action: "deny ipv6 2001:db8:1000::/64 any"
      - sequence: 10
        action: "permit ipv6 2001:db8::/32 any"
