---
### VRFs ###

vrfs:
  - name: MGMT
    ip_routing: false
  - name: TENANT_A_PROJECT01
    tenant: Tenant_A
    ip_routing: true
  - name: TENANT_A_PROJECT02
    tenant: Tenant_A
    ip_routing: true
  - name: BLAH
  - name: defauls
  - name: defaulu
  - name: TEST1
    ip_routing: true
    ipv6_routing: true
  - name: TEST2
    ip_routing: false
    ipv6_routing: false
    ip_routing_ipv6_interfaces: true
  - name: default
    ip_routing: true
    ipv6_routing: true
    ip_routing_ipv6_interfaces: true
