objects:
  role: {}
plugins:
  become: {}
  cache: {}
  callback: {}
  cliconf: {}
  connection: {}
  filter:
    add_md_toc:
      description: Parse the input Markdown and add a Table of Contents between the
        toc_markers.
      name: add_md_toc
      version_added: '3.2'
    decrypt:
      description: Decrypt supported EOS passwords.
      name: decrypt
      version_added: 3.8.0
    default:
      description: Returns input value if defined and is not none. Otherwise, return
        default value.
      name: default
      version_added: '2.0'
    encrypt:
      description: Encrypt supported EOS passwords
      name: encrypt
      version_added: 3.8.0
    hide_passwords:
      description: Replace a value by "<removed>"
      name: hide_passwords
      version_added: 4.0.0
    is_in_filter:
      description: Returns `True` if the input hostname matches the `hostname_filter`.
      name: is_in_filter
      version_added: '1.1'
    list_compress:
      description: Compress a list of integers to a range string.
      name: list_compress
      version_added: '1.0'
    natural_sort:
      description: Sort an input list with natural sorting.
      name: natural_sort
      version_added: 1.0.0
    range_expand:
      description: Expand a range of interfaces or list of ranges and return as a
        list of strings.
      name: range_expand
      version_added: 3.4.0
    snmp_hash:
      description: Compute localized SNMP passphrases
      name: snmp_hash
      version_added: 3.6.0
    status_render:
      description: Convert Text to EMOJI code.
      name: status_render
      version_added: 1.1.1
  httpapi: {}
  inventory: {}
  lookup: {}
  module:
    configlet_build_config:
      description: Build arista.cvp.configlet configuration.
      name: configlet_build_config
      namespace: ''
      version_added: 1.0.0
    cv_workflow:
      description: Deploy various objects to CloudVision
      name: cv_workflow
      namespace: ''
      version_added: 4.7.0
    eos_cli_config_gen:
      description: Generate AVD EOS device configurations and documentations
      name: eos_cli_config_gen
      namespace: ''
      version_added: 4.9.0
    eos_designs_documentation:
      description: Generate AVD Fabric Documentation
      name: eos_designs_documentation
      namespace: ''
      version_added: 5.0.0
    eos_designs_facts:
      description: Set eos_designs facts
      name: eos_designs_facts
      namespace: ''
      version_added: 3.5.0
    eos_designs_structured_config:
      description: Generate AVD EOS Designs structured configuration
      name: eos_designs_structured_config
      namespace: ''
      version_added: 4.0.0
    eos_validate_state_reports:
      description: Generates validation reports for the eos_validate_state role
      name: eos_validate_state_reports
      namespace: ''
      version_added: 4.5.0
    eos_validate_state_runner:
      description: Uses ANTA for eos_validate_state role
      name: eos_validate_state_runner
      namespace: ''
      version_added: 4.4.0
    inventory_to_container:
      description: Transform information from inventory to arista.cvp collection
      name: inventory_to_container
      namespace: ''
      version_added: 1.0.0
    set_vars:
      description: Set vars as ansible_facts.
      name: set_vars
      namespace: ''
      version_added: 4.0.0
    verify_requirements:
      description: Verify Python requirements when running AVD
      name: verify_requirements
      namespace: ''
      version_added: 4.0.0
  netconf: {}
  shell: {}
  strategy: {}
  test:
    contains:
      description: Test if a list contains one or more of the supplied values.
      name: contains
      version_added: '2.0'
    defined:
      description: Test if the value is not `Undefined` or `None`.
      name: defined
      version_added: '2.0'
  vars:
    global_vars:
      description: Variable plugins to allow loading global_vars with less precedence
        than group_vars or host_vars
      name: global_vars
      version_added: 4.0.0
version: 5.1.0
