# Copyright (c) 2024 Arista Networks, Inc.
# Use of this source code is governed by the Apache License 2.0
# that can be found in the LICENSE file.
# yaml-language-server: $schema=../../../_schema/avd_meta_schema.json
# Line above is used by RedHat's YAML Schema vscode extension
# Use Ctrl + Space to get suggestions for every field. Autocomplete will pop up after typing 2 letters.
type: dict
keys:
  avd_eos_designs_enforce_duplication_checks_across_all_models:
    documentation_options:
      table: role-settings
    type: bool
    default: false
    description: |-
      PREVIEW: This option is marked as "preview", while we refactor the code to conform to the described behavior.
      When this is enabled, the generation of Structured Config in `eos_designs` will prevent duplicate objects generated
      by different input models. This will also improve performance since `eos_designs` will not maintain separate copied of the Structured Configuration.
      As an example, if you define an Ethernet interface under `l3_edge` and use the same interface for connectivity under `servers`:
      - With this option disabled (default), AVD will merge these configurations together for the interface and not raise an error.
      - With this option enabled, AVD will raise an error about duplicate interface definitions.
