---
# Minimum config to only test the specific feature.
l3leaf:
  defaults:
    loopback_ipv4_pool: 10.42.0.0/24
    bgp_as: 42
    vtep_loopback_ipv4_pool: 10.43.0.0/24
  nodes:
    - name: duplicate-interfaces-connected-endpoints
      id: 42

type: l3leaf

servers:
  - name: server01_ES1
    adapters:
      - endpoint_ports: [ Eth1 ]
        switch_ports: [ Ethernet10 ]
        switches: [ duplicate-interfaces-connected-endpoints ]

  - name: server02
    adapters:
      - endpoint_ports: [ Eth2 ]
        switch_ports: [ Ethernet10 ]
        switches: [ duplicate-interfaces-connected-endpoints ]

expected_error_message: >-
  Found duplicate objects with conflicting data while generating configuration for EthernetInterfaces.
  {'name': 'Ethernet10', 'description': 'SERVER_server02_Eth2', 'shutdown': False, 'peer': 'server02', 'peer_interface': 'Eth2',
  'peer_type': 'server', 'switchport': {'enabled': True}}
  conflicts with
  {'name': 'Ethernet10', 'description': 'SERVER_server01_ES1_Eth1', 'shutdown': False, 'peer': 'server01_ES1', 'peer_interface': 'Eth1',
  'peer_type': 'server', 'switchport': {'enabled': True}}.
