---
type: l3leaf
fabric_name: FAILURE_CONNECTED_ENDPOINT_PORT_PROFILE_DOES_NOT_EXIST_IN_FACTS

port_profiles:
  - profile: PROFILE-1

l3leaf:
  nodes:
    - name: failure-connected-endpoint-port-profile-does-not-exist-in-facts
      loopback_ipv4_pool: 192.168.42.0/24
      vtep_loopback_ipv4_pool: 192.168.255.0/24
      bgp_as: 65042
      id: 1
      filter:
        only_vlans_in_use: true

servers:
  - name: TEST-ENDPOINT
    adapters:
      - switches: [failure-connected-endpoint-port-profile-does-not-exist-in-facts]
        switch_ports: [Ethernet9]
        profile: THIS-PROFILE-DOES-NOT-EXIST
        # Setting VLANs to trigger merging of adapters in facts phase
        vlans: :42,666"

expected_error_message: >-
  Profile 'THIS-PROFILE-DOES-NOT-EXIST' applied under 'servers[name=TEST-ENDPOINT].adapters[0]'
  does not exist in `port_profiles` for host 'failure-connected-endpoint-port-profile-does-not-exist-in-facts'.
