type: l2leaf

l2leaf:
  defaults:
    platform: vEOS-LAB
    uplink_switches: [ UPLINK-MLAG-STRUCTURED-CONFIG-L3LEAF1A, UPLINK-MLAG-STRUCTURED-CONFIG-L3LEAF1B ]
    uplink_interfaces: [ Ethernet1, Ethernet2 ]
    uplink_structured_config:
      storm_control:
        broadcast:
          level: 25
        unknown_unicast:
          level: 25
    mlag_interfaces: [ Ethernet3, Ethernet4 ]
    mlag_peer_ipv4_pool: 10.255.252.0/24
    mlag_port_channel_structured_config:  # Setting structured config here but it is overridden by 'null' on group level and applied again on node level.
      description: "Port-channel description not being used because it is overridden by 'null' on node-group level."

    spanning_tree_mode: mstp
    spanning_tree_priority: 16384
  node_groups:
    - group: UPLINK-MLAG-STRUCTURED-CONFIG-L2LEAF1
      # Testing the inheritance works correctly when nullifying a dict in the group and then applying a new one per node.
      mlag_port_channel_structured_config: null
      # Testing merging of uplink_structured_config which is a dict type with no schema.
      uplink_structured_config:
        switchport:
          trunk:
            native_vlan_tag: true
      nodes:
        - name: UPLINK-MLAG-STRUCTURED-CONFIG-L2LEAF1A
          id: 1
          mgmt_ip: 192.168.201.201/24
          uplink_switch_interfaces: [ Ethernet5, Ethernet5 ]
          mlag_port_channel_structured_config:
            storm_control:
              broadcast:
                level: 25
              unknown_unicast:
                level: 25
            switchport:
              trunk:
                native_vlan_tag: true
        - name: UPLINK-MLAG-STRUCTURED-CONFIG-L2LEAF1B
          id: 2
          mgmt_ip: 192.168.201.201/24
          uplink_switch_interfaces: [ Ethernet6, Ethernet6 ]
          mlag_port_channel_structured_config:
            storm_control:
              broadcast:
                level: 25
              unknown_unicast:
                level: 25
            switchport:
              trunk:
                native_vlan_tag: true
