---
name: "CV integration testing"

# "on": pull_request
"on": workflow_dispatch

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}

env:
  # Set -vvv is ACTIONS_STEP_DEBUG is set
  # Apparently it is set in secrets when running with debug
  ANSIBLE_VERBOSITY: ${{ secrets.ACTIONS_STEP_DEBUG && 3 || 0 }}
  AVD_NEVER_RUN_FROM_SOURCE: 1
  PY_COLORS: 1 # allows molecule colors to be passed to GitHub Actions
  ANSIBLE_FORCE_COLOR: 1 # allows ansible colors to be passed to GitHub Actions

jobs:
  # ----------------------------------------------- #
  # CV INTEGRATION MOLECULE TEST FOR CV_WORKFLOW    #
  # ----------------------------------------------- #
  molecule_cv_workflow:
    name: Run molecule test for new cvp integration
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        avd_scenario:
          - 'cv_workflow'
        ansible_version:
          - 'ansible-core<2.19.0 --upgrade'
    steps:
      - uses: actions/checkout@v4
      - name: Run molecule action
        env:
          CVAAS_AAWG_CI: ${{ secrets.CVAAS_AAWG_CI }}
        uses: arista-netdevops-community/action-molecule-avd@v1.8.1
        with:
          molecule_parentdir: 'ansible_collections/arista/avd'
          molecule_command: 'test'
          molecule_args: '--scenario-name ${{ matrix.avd_scenario }}'
          pip_file: .github/requirements-ci.txt
          galaxy_file: "ansible_collections/arista/avd/collections.yml"
          ansible: ${{ matrix.ansible_version }}
          check_git: true
          check_git_enforced: true

  # ------------------------------------------- #
  # CV INTEGRATION MOLECULE TEST FOR CV_DEPLOY  #
  # ------------------------------------------- #
  molecule_cv_deploy:
    name: Run molecule test for new cvp integration
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        avd_scenario:
          - 'cv_deploy'
        ansible_version:
          - 'ansible-core<2.19.0 --upgrade'
    steps:
      - uses: actions/checkout@v4
      - name: Run molecule action
        env:
          CVAAS_AAWG_CI: ${{ secrets.CVAAS_AAWG_CI }}
        uses: arista-netdevops-community/action-molecule-avd@v1.8.1
        with:
          molecule_parentdir: 'ansible_collections/arista/avd'
          molecule_command: 'test'
          molecule_args: '--scenario-name ${{ matrix.avd_scenario }}'
          pip_file: .github/requirements-ci.txt
          galaxy_file: "ansible_collections/arista/avd/collections.yml"
          ansible: ${{ matrix.ansible_version }}
          check_git: true
          check_git_enforced: true
